<?php

/**
 * BaseSensores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $identificador
 * @property text $ubicacion
 * @property bigint $ptomonit_id
 * @property Ptomonit $Ptomonit
 * @property Doctrine_Collection $Sensores
 * 
 * @method text                getIdentificador() Returns the current record's "identificador" value
 * @method text                getUbicacion()     Returns the current record's "ubicacion" value
 * @method bigint              getPtomonitId()    Returns the current record's "ptomonit_id" value
 * @method Ptomonit            getPtomonit()      Returns the current record's "Ptomonit" value
 * @method Doctrine_Collection getSensores()      Returns the current record's "Sensores" collection
 * @method Sensores            setIdentificador() Sets the current record's "identificador" value
 * @method Sensores            setUbicacion()     Sets the current record's "ubicacion" value
 * @method Sensores            setPtomonitId()    Sets the current record's "ptomonit_id" value
 * @method Sensores            setPtomonit()      Sets the current record's "Ptomonit" value
 * @method Sensores            setSensores()      Sets the current record's "Sensores" collection
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSensores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sensores');
        $this->hasColumn('identificador', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('ubicacion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('ptomonit_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ptomonit', array(
             'local' => 'ptomonit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Registro as Sensores', array(
             'local' => 'id',
             'foreign' => 'sensor_id'));
    }
}