<?php

/**
 * BaseUnidades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $unidad
 * @property Doctrine_Collection $Unidades
 * 
 * @method text                getUnidad()   Returns the current record's "unidad" value
 * @method Doctrine_Collection getUnidades() Returns the current record's "Unidades" collection
 * @method Unidades            setUnidad()   Sets the current record's "unidad" value
 * @method Unidades            setUnidades() Sets the current record's "Unidades" collection
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnidades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unidades');
        $this->hasColumn('unidad', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cargos as Unidades', array(
             'local' => 'id',
             'foreign' => 'unidades_id'));
    }
}