<?php

/**
 * BaseRecintos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property text $tarifa
 * 
 * @method text     getNombre() Returns the current record's "nombre" value
 * @method text     getTarifa() Returns the current record's "tarifa" value
 * @method Recintos setNombre() Sets the current record's "nombre" value
 * @method Recintos setTarifa() Sets the current record's "tarifa" value
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecintos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recintos');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('tarifa', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}