<?php

/**
 * BaseRegistro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property float $potencia
 * @property timestamp $registrado_at
 * @property bigint $sensor_id
 * @property Sensores $Sensores
 * 
 * @method float     getPotencia()      Returns the current record's "potencia" value
 * @method timestamp getRegistradoAt()  Returns the current record's "registrado_at" value
 * @method bigint    getSensorId()      Returns the current record's "sensor_id" value
 * @method Sensores  getSensores()      Returns the current record's "Sensores" value
 * @method Registro  setPotencia()      Sets the current record's "potencia" value
 * @method Registro  setRegistradoAt()  Sets the current record's "registrado_at" value
 * @method Registro  setSensorId()      Sets the current record's "sensor_id" value
 * @method Registro  setSensores()      Sets the current record's "Sensores" value
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registro');
        $this->hasColumn('potencia', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'scale' => 2,
             ));
        $this->hasColumn('registrado_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('sensor_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sensores', array(
             'local' => 'sensor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}