<?php

/**
 * BasePtoMonit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property float $potenciaI
 * 
 * @method text     getNombre()    Returns the current record's "nombre" value
 * @method float    getPotenciaI() Returns the current record's "potenciaI" value
 * @method PtoMonit setNombre()    Sets the current record's "nombre" value
 * @method PtoMonit setPotenciaI() Sets the current record's "potenciaI" value
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePtoMonit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pto_monit');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('potenciaI', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}