<?php

/**
 * BasePtomonit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property text $ubicacion
 * @property float $potenciaI
 * @property text $mapa
 * @property bigint $recinto_id
 * @property Recintos $Recintos
 * @property Doctrine_Collection $Ptomonits
 * 
 * @method text                getNombre()     Returns the current record's "nombre" value
 * @method text                getUbicacion()  Returns the current record's "ubicacion" value
 * @method float               getPotenciaI()  Returns the current record's "potenciaI" value
 * @method text                getMapa()       Returns the current record's "mapa" value
 * @method bigint              getRecintoId()  Returns the current record's "recinto_id" value
 * @method Recintos            getRecintos()   Returns the current record's "Recintos" value
 * @method Doctrine_Collection getPtomonits()  Returns the current record's "Ptomonits" collection
 * @method Ptomonit            setNombre()     Sets the current record's "nombre" value
 * @method Ptomonit            setUbicacion()  Sets the current record's "ubicacion" value
 * @method Ptomonit            setPotenciaI()  Sets the current record's "potenciaI" value
 * @method Ptomonit            setMapa()       Sets the current record's "mapa" value
 * @method Ptomonit            setRecintoId()  Sets the current record's "recinto_id" value
 * @method Ptomonit            setRecintos()   Sets the current record's "Recintos" value
 * @method Ptomonit            setPtomonits()  Sets the current record's "Ptomonits" collection
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePtomonit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ptomonit');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('ubicacion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('potenciaI', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('mapa', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('recinto_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Recintos', array(
             'local' => 'recinto_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Sensores as Ptomonits', array(
             'local' => 'id',
             'foreign' => 'ptomonit_id'));
    }
}