<?php

/**
 * BaseTarifas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property Doctrine_Collection $Cargos
 * 
 * @method text                getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getCargos() Returns the current record's "Cargos" collection
 * @method Tarifas             setNombre() Sets the current record's "nombre" value
 * @method Tarifas             setCargos() Sets the current record's "Cargos" collection
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarifas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarifas');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cargos', array(
             'local' => 'id',
             'foreign' => 'tarifa_id'));
    }
}