<?php

/**
 * BaseCargos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property float $valor
 * @property text $unidad
 * 
 * @method text   getNombre() Returns the current record's "nombre" value
 * @method float  getValor()  Returns the current record's "valor" value
 * @method text   getUnidad() Returns the current record's "unidad" value
 * @method Cargos setNombre() Sets the current record's "nombre" value
 * @method Cargos setValor()  Sets the current record's "valor" value
 * @method Cargos setUnidad() Sets the current record's "unidad" value
 * 
 * @package    sgeudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCargos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cargos');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('valor', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('unidad', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}