<?php

/**
 * PtoMonitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PtoMonitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PtoMonitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PtoMonit');
    }
}