<?php

/**
 * RecintosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecintosTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object RecintosTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Recintos');
  }

  public function getRecintos() {
    return Doctrine_Query::create()
                    ->select('*')
                    ->from('Recintos')
                    ->OrderBy('nombre asc')
                    ->execute();
  }

}