<?php

/**
 * SensoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SensoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SensoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sensores');
    }
}