<?php

/**
 * TarifasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TarifasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TarifasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tarifas');
    }
}