# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css,style.css,invalid.css]

  javascripts:    [jquery-1.3.2.min.js,simpla.jquery.configuration.js,facebox.js,jquery.wysiwyg.js,jquery.datePicker.js,jquery.date.js]

  has_layout:     true
  layout:         layout
