<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('cargos', 'codigo', 'varchar', '5', array(
             'notnull' => '1',
             'unique' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('cargos', 'codigo');
    }
}