# config/doctrine/schema.yml
---
Tarifas:
  columns:
    nombre:     { type: text, notnull: true }


Cargos:
  columns:
    nombre:       { type: text, notnull: true }
    valor:        { type: float, notnull: true, scale: 4}
    tarifa_id:    { type: bigint(20), notnull: true }
    unidades_id:  { type: bigint(20), notnull: true }
  relations:
    Tarifas:      { onDelete: CASCADE, local: tarifa_id, foreign: id, foreignAlias: Cargos }
    Unidades:     { onDelete: CASCADE, local: unidades_id, foreign: id, foreignAlias: Unidades }
    
Recintos:
  columns:
    nombre:     { type: text, notnull: true }
    tarifa:     { type: text, notnull: true }

PtoMonit:
  columns:
    nombre:     { type: text, notnull: true }
    potenciaI:  { type: float, notnull: true }

Unidades:
  columns:
    unidad:     { type: text, notnull: true }

